image:
  repository: api
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

configmap:
  HOST: "0.0.0.0"
  PORT: "8080"
  RUST_LOG: "info"
  DATABASE_URL: "postgres://myuser:mypass@postgresql-dev:5432/mydb?sslmode=disable"
